services: 

    kafka:
        image: "bitnami/kafka:latest"
        hostname: kafka
        container_name: kafka
        ports:
        - "9092:9092"
        - "9093:9093"

        environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_KRAFT_CLUSTER_ID=Hjfd984UFJ23kfds       
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        - ALLOW_PLAINTEXT_LISTENER=yes

        volumes:
        - kafka_data:/bitnami/kafka


    mongodb:
        image: mongo
        ports:
            - "27017:27017"        
        volumes: 
        - ./mongo:/data/db
            
volumes:
  kafka_data:
  mongo:        