services: 

    kafka1:
        image: "bitnami/kafka:latest"
        hostname: kafka1
        container_name: kafka1
        ports:
        - "9092:9092"

        environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_KRAFT_CLUSTER_ID=Hjfd984UFJ23kfds   
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
        - KAFKA_DEFAULT_REPLICATION_FACTOR=3
        - KAFKA_NUM_PARTITIONS=3
        - KAFKA_MIN_INSYNC_REPLICAS=2        
        volumes:
        - kafka1_data:/bitnami/kafka
        restart: on-failure
        healthcheck:
            test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5

    kafka2:
        image: "bitnami/kafka:latest"
        hostname: kafka2
        container_name: kafka2
        ports:
        - "9094:9094"

        environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_KRAFT_CLUSTER_ID=Hjfd984UFJ23kfds
        - KAFKA_CFG_NODE_ID=2
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9094,CONTROLLER://kafka2:9093
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
        - KAFKA_DEFAULT_REPLICATION_FACTOR=3
        - KAFKA_NUM_PARTITIONS=3
        - KAFKA_MIN_INSYNC_REPLICAS=2        
        volumes:
        - kafka2_data:/bitnami/kafka
        restart: on-failure
        healthcheck:
            test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9094 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5        

    kafka3:
        image: "bitnami/kafka:latest"
        hostname: kafka3
        container_name: kafka3
        ports:
        - "9096:9096"

        environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_KRAFT_CLUSTER_ID=Hjfd984UFJ23kfds
        - KAFKA_CFG_NODE_ID=3
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9096,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9096,CONTROLLER://kafka3:9093
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
        - KAFKA_DEFAULT_REPLICATION_FACTOR=3
        - KAFKA_NUM_PARTITIONS=3 
        - KAFKA_MIN_INSYNC_REPLICAS=2
        volumes:
        - kafka3_data:/bitnami/kafka
        restart: on-failure
        healthcheck:
            test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9096 || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5              

    mongodb:
        image: mongo
        ports:
            - "27017:27017"        
        volumes: 
        - mongo:/data/db
        restart: on-failure
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5

    generator:
        build: ./data_generator    
        restart: on-failure  
        depends_on:
            - kafka1 
            - kafka2  
            - kafka3                           
            
    producer:
        build: ./kafka/producer
        environment:
        - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9094,kafka3:9096
        - KAFKA_TOPIC=sensor-data
        depends_on:
            kafka1:
                condition: service_healthy
            kafka2:
                condition: service_healthy
            kafka3:
                condition: service_healthy
            mongodb:
                condition: service_healthy        
        restart: on-failure

    consumer:
        build: ./kafka/consumer
        environment:
        - KAFKA_BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9094,kafka3:9096
        - MONGO_URI=mongodb://mongodb:27017/
        - KAFKA_TOPIC=sensor-data
        - KAFKA_GROUP_ID=mongo-writer-group
        depends_on:
            kafka1:
                condition: service_healthy
            kafka2:
                condition: service_healthy
            kafka3:
                condition: service_healthy
            mongodb:
                condition: service_healthy
        restart: on-failure

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"        
        volumes:    
            - prometheus-data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        restart: on-failure    

    grafana:
        image: grafana/grafana:latest          
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource      
        volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning 
            - ./grafana/dashboards:/var/lib/grafana/dashboards    
        restart: on-failure


#Prometheus exporters
    kafka-exporter:
        image: danielqsj/kafka-exporter:latest
        container_name: kafka-exporter
        command: 
                - "--kafka.server=kafka1:9092"
                - "--kafka.server=kafka2:9094"
                - "--kafka.server=kafka3:9096"
                - "--web.listen-address=:9308"
        depends_on:
            kafka1:
                condition: service_healthy
            kafka2:
                condition: service_healthy
            kafka3:
                condition: service_healthy
        ports:
            - "9308:9308" 
        restart: on-failure



    mongodb-exporter:
        image: bitnami/mongodb-exporter:latest
        container_name: mongodb-exporter
        environment:
        - MONGODB_URI=mongodb://mongodb:27017
        depends_on:
        - mongodb
        restart: on-failure

    query_api:
        build: ./query_api
        ports:
            - "5001:5001"
        depends_on:
            - mongodb
        restart: on-failure
    

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:          
  mongo:        
  prometheus-data:
  grafana-data: