services: 

    kafka:
        image: "bitnami/kafka:latest"
        hostname: kafka
        container_name: kafka
        ports:
        - "9092:9092"

        environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_KRAFT_CLUSTER_ID=Hjfd984UFJ23kfds       
        - KAFKA_CFG_NODE_ID=0
        - KAFKA_CFG_PROCESS_ROLES=controller,broker
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - ALLOW_PLAINTEXT_LISTENER=yes

        volumes:
        - kafka_data:/bitnami/kafka
        restart: on-failure

    mongodb:
        image: mongo
        ports:
            - "27017:27017"        
        volumes: 
        - ./mongo:/data/db

    generator:
        build:
            context: ./data_generator    
        restart: on-failure  
        depends_on:
            - kafka  
            

    producer:
        build: ./kafka/producer
        environment:
        - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
        - KAFKA_TOPIC=sensor-data
        depends_on:
        - kafka
        - generator
        restart: on-failure

    consumer:
        build: ./kafka/consumer
        environment:
        - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
        - MONGO_URI=mongodb://mongodb:27017/
        - KAFKA_TOPIC=sensor-data
        - KAFKA_GROUP_ID=mongo-writer-group
        depends_on:
        - kafka
        - mongodb
        restart: on-failure

volumes:
  kafka_data:
  mongo:        