global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:  

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: kafka-exporter
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: mongodb-exporter
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  - job_name: generator
    static_configs:
      - targets: ["generator:5000"]      