apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    jsonData:
      allowed_hosts:
        - "https://jsonplaceholder.typicode.com"
        - "http://localhost"
