apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Infinity
    uid: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://query_api:5001 
    jsonData:
      authentication_method: none
