{
 "title": "Sensor_data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "temperature", "text": "temperature", "type": "number" },
      { "selector": "time", "text": "time", "type": "timestamp" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/sensors",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Cloud",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "columns": [
      { "selector": "cloud", "text": "cloud", "type": "number" },
      { "selector": "time", "text": "time", "type": "timestamp" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/sensors",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Data Generation Errors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "generator_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total events generated",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "generator_events_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "columns": [
      { "selector": "humidity", "text": "humidity", "type": "number" },
      { "selector": "time", "text": "time", "type": "timestamp" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/sensors",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Percipation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 6 },
   "targets": [
    {
     "columns": [
      { "selector": "percipation", "text": "percipation", "type": "number" },
      { "selector": "time", "text": "time", "type": "timestamp" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/sensors",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Mongo Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "columns": [
      { "selector": "wind", "text": "wind", "type": "number" },
      { "selector": "time", "text": "time", "type": "timestamp" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "/sensors",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_consumergroup_lag_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer Offset",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Brokers available",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "__auto" }
   ]
  }
 ]
}